pipeline {
    agent any

    environment {
        AWS_ACCOUNT_ID = "792339582456"
        AWS_REGION = "ap-south-1"
        ECR_REPO = "clipboard-devops"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Git Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/harshchaudhary01/clipboard-devops-project'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t $ECR_REPO:$IMAGE_TAG ./app
                '''
            }
        }

        stage('Configure AWS Credentials') {
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds']
                ]) {

                    sh '''
                    aws sts get-caller-identity
                    '''
                }
            }
        }

        stage('Login to AWS ECR') {
            steps {

                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds']
                ]) {

                    sh '''
                    aws ecr get-login-password --region $AWS_REGION | \
                    docker login --username AWS \
                    --password-stdin \
                    $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                    '''
                }
            }
        }

        stage('Tag Docker Image') {
            steps {
                sh '''
                docker tag $ECR_REPO:$IMAGE_TAG \
                $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
                '''
            }
        }

        stage('Push Docker Image to ECR') {
            steps {

                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds']
                ]) {

                    sh '''
                    docker push \
                    $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
                    '''
                }
            }
        }

        stage('Deploy Container on EC2') {
            steps {

                withCredentials([
                    string(credentialsId: 'mongo-uri', variable: 'MONGO_URI'),
                    [$class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds']
                ]) {

                    sh '''

                    docker rm -f clipboard-container || true

                    docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

                    docker run -d \
                    --restart unless-stopped \
                    --name clipboard-container \
                    -p 3000:3000 \
                    -e MONGODB_URI=$MONGO_URI \
                    $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

                    '''
                }
            }
        }

        stage('Verify Prometheus Monitoring') {
            steps {
                sh '''
                echo "Checking Prometheus Container..."

                docker ps | grep prometheus

                curl -f http://localhost:9090/-/healthy || exit 1

                echo "Prometheus is Running Successfully!"
                '''
            }
        }

        stage('Verify Grafana Dashboard') {
            steps {
                sh '''
                echo "Checking Grafana Container..."

                docker ps | grep grafana

                curl -f http://localhost:3001/api/health || exit 1

                echo "Grafana is Running Successfully!"
                '''
            }
        }
    }

    post {

        success {
            echo 'Deployment Successful!'
        }

        failure {
            echo 'Pipeline Failed!'
        }
    }
}